using RealEstateAnalysis.Data.Entities.LocationAnalysis;

namespace RealEstateAnalysis.Data.Abstract.LocationAnalysis
{
    public interface ICityRepository
    {
        Task DeleteAsync(City city);

        Task<List<City>> GetAllAsync(string userId, bool asNoTracking = false);

        Task<City> GetByIdAsync(long id, string userId, bool asNoTracking = false);

        Task SaveOrUpdateAsync(City city);

        Task SaveOrUpdateAsync(List<City> cities);

        Task RemoveAllAutoGenerated();
    }
}