CREATE TABLE [LocationAnalysis].[Cities] (
    [Id]                                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [CreatedDate]                        DATETIME2 (7)   NOT NULL,
    [ModifiedDate]                       DATETIME2 (7)   NULL,
    [PopulationInYearStart]              INT             NOT NULL,
    [PopulationInYearEnd]                INT             NOT NULL,
    [MedianHouseholdIncomeInYearStart]   DECIMAL (18, 2) NOT NULL,
    [MedianHouseholdIncomeInYearEnd]     DECIMAL (18, 2) NOT NULL,
    [MedianHouseOrCondoValueInYearStart] DECIMAL (18, 2) NOT NULL,
    [MedianHouseOrCondoValueInYearEnd]   DECIMAL (18, 2) NOT NULL,
    [CrimeIndexInYearStart]              DECIMAL (18, 2) NOT NULL,
    [CrimeIndexInYearEnd]                DECIMAL (18, 2) NOT NULL,
    [CityName]                           NVARCHAR (500)  DEFAULT (N'') NOT NULL,
    [StateId]                            BIGINT          DEFAULT (CONVERT([bigint],(0))) NOT NULL,
    [UserId]                             NVARCHAR (450)  DEFAULT (N'') NOT NULL,
    [RecentYearJobsGrowthRate]           DECIMAL (18, 2) DEFAULT ((0.0)) NOT NULL,
    [MedianHouseOrCondoValueYearEnd]     INT             DEFAULT ((0)) NOT NULL,
    [MedianHouseholdIncomeYearEnd]       INT             DEFAULT ((0)) NOT NULL,
    [PopulationYearEnd]                  INT             DEFAULT ((0)) NOT NULL,
    [NumberOfJobsAdded]                  INT             DEFAULT ((0)) NOT NULL,
    [CrimeIndexYearEnd]                  INT             DEFAULT ((0)) NOT NULL,
    [CrimeIndexYearStart]                INT             DEFAULT ((0)) NOT NULL,
    [IsFavorite]                         BIT             DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [MedianHouseOrCondoValueYearStart]   INT             DEFAULT ((0)) NOT NULL,
    [MedianHouseholdIncomeYearStart]     INT             DEFAULT ((0)) NOT NULL,
    [PopulationYearStart]                INT             DEFAULT ((0)) NOT NULL,
    [AutoGeneratedDate]                  DATETIME2 (7)   NULL,
    CONSTRAINT [PK_Cities] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Cities_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_Cities_States_StateId] FOREIGN KEY ([StateId]) REFERENCES [Lookup].[States] ([Id]) ON DELETE CASCADE
);














GO
CREATE NONCLUSTERED INDEX [IX_Cities_UserId]
    ON [LocationAnalysis].[Cities]([UserId] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_Cities_StateId]
    ON [LocationAnalysis].[Cities]([StateId] ASC);

