using Microsoft.EntityFrameworkCore.Migrations;

namespace RealEstateAnalysis.Data.Migrations
{
    public partial class city_data_urls : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "CrimeIndexYearEnd",
                schema: "LocationAnalysis",
                table: "Cities",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "CrimeIndexYearStart",
                schema: "LocationAnalysis",
                table: "Cities",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                schema: "LocationAnalysis",
                table: "Cities",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.CreateTable(
                name: "CityDataCityUrl",
                schema: "LocationAnalysis",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Url = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    ScanDate = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CityDataCityUrl", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CityDataCityUrl",
                schema: "LocationAnalysis");

            migrationBuilder.DropColumn(
                name: "CrimeIndexYearEnd",
                schema: "LocationAnalysis",
                table: "Cities");

            migrationBuilder.DropColumn(
                name: "CrimeIndexYearStart",
                schema: "LocationAnalysis",
                table: "Cities");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                schema: "LocationAnalysis",
                table: "Cities");
        }
    }
}