SET IDENTITY_INSERT [LocationAnalysis].[CityDataStateUrls] ON

INSERT INTO [LocationAnalysis].[CityDataStateUrls]([Id], [Url])
SELECT * FROM (VALUES 
	(1, 'http://www.city-data.com/city/Alabama.html'),
	(2, 'http://www.city-data.com/city/Alaska.html'),
	(3, 'http://www.city-data.com/city/Arkansas.html'),
	(4, 'http://www.city-data.com/city/Arizona.html'),
	(5, 'http://www.city-data.com/city/California.html'),
	(6, 'http://www.city-data.com/city/Colorado.html'),
	(7, 'http://www.city-data.com/city/Connecticut.html'),
	(8, 'http://www.city-data.com/city/Delaware.html'),
	(9, 'http://www.city-data.com/city/District-of-Columbia.html'),
	(10, 'http://www.city-data.com/city/Florida.html'),
	(11, 'http://www.city-data.com/city/Georgia.html'),
	(12, 'http://www.city-data.com/city/Hawaii.html'),
	(13, 'http://www.city-data.com/city/Idaho.html'),
	(14, 'http://www.city-data.com/city/Illinois.html'),
	(15, 'http://www.city-data.com/city/Indiana.html'),
	(16, 'http://www.city-data.com/city/Iowa.html'),
	(17, 'http://www.city-data.com/city/Kansas.html'),
	(18, 'http://www.city-data.com/city/Kentucky.html'),
	(19, 'http://www.city-data.com/city/Louisiana.html'),
	(20, 'http://www.city-data.com/city/Maine.html'),
	(21, 'http://www.city-data.com/city/Maryland.html'),
	(22, 'http://www.city-data.com/city/Massachusetts.html'),
	(23, 'http://www.city-data.com/city/Michigan.html'),
	(24, 'http://www.city-data.com/city/Minnesota.html'),
	(25, 'http://www.city-data.com/city/Mississippi.html'),
	(26, 'http://www.city-data.com/city/Missouri.html'),
	(27, 'http://www.city-data.com/city/Montana.html'),
	(28, 'http://www.city-data.com/city/Nebraska.html'),
	(29, 'http://www.city-data.com/city/Nevada.html'),
	(30, 'http://www.city-data.com/city/New-Hampshire.html'),
	(31, 'http://www.city-data.com/city/New-Jersey.html'),
	(32, 'http://www.city-data.com/city/New-Mexico.html'),
	(33, 'http://www.city-data.com/city/New-York.html'),
	(34, 'http://www.city-data.com/city/North-Carolina.html'),
	(35, 'http://www.city-data.com/city/North-Dakota.html'),
	(36, 'http://www.city-data.com/city/Ohio.html'),
	(37, 'http://www.city-data.com/city/Oklahoma.html'),
	(38, 'http://www.city-data.com/city/Oregon.html'),
	(39, 'http://www.city-data.com/city/Pennsylvania.html'),
	(40, 'http://www.city-data.com/city/Rhode-Island.html'),
	(41, 'http://www.city-data.com/city/South-Carolina.html'),
	(42, 'http://www.city-data.com/city/South-Dakota.html'),
	(43, 'http://www.city-data.com/city/Tennessee.html'),
	(44, 'http://www.city-data.com/city/Texas.html'),
	(45, 'http://www.city-data.com/city/Utah.html'),
	(46, 'http://www.city-data.com/city/Vermont.html'),
	(47, 'http://www.city-data.com/city/Virginia.html'),
	(48, 'http://www.city-data.com/city/Washington.html'),
	(49, 'http://www.city-data.com/city/West-Virginia.html'),
	(50, 'http://www.city-data.com/city/Wisconsin.html'),
	(51, 'http://www.city-data.com/city/Wyoming.html')
) AS cols([Id], [Url]) WHERE cols.Id NOT IN (SELECT Id FROM [LocationAnalysis].[CityDataStateUrls])

SET IDENTITY_INSERT [LocationAnalysis].[CityDataStateUrls] OFF
GO